In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('DatosProcesados.csv')
df.head()

,timestamp,turno,operador_id,maquina_id,producto_id,tiempo_ciclo,tipo_fallo,cantidad_producida,unidades_defectuosas,eficiencia_porcentual,consumo_energia,paradas_programadas,paradas_imprevistas,fallo_detectado_bool,vib_temp_interaction,humedad_extrema,eficiencia
0,2023-01-01 00:00:00,3,16,8,14,106.356684,False,108,3,87.021704,13.131580,0,1,False,NaN,0,120.659554
1,2023-01-01 01:00:00,1,18,8,12,106.147220,True,86,2,81.200758,13.348221,0,0,True,41.336724,0,103.447310
2,2023-01-01 02:00:00,3,5,7,14,122.517733,False,103,0,79.104477,15.461715,3,0,False,36.308811,0,130.207548
3,2023-01-01 03:00:00,3,4,6,15,123.641235,False,104,2,84.176537,16.156453,4,0,False,43.675360,0,121.173909
4,2023-01-01 04:00:00,1,13,6,7,126.276992,False,119,1,93.535084,12.573939,0,0,False,50.056219,1,126.155871

In [3]:
y = df['cantidad_producida']
X = df.drop(columns=['cantidad_producida','timestamp','paradas_programadas','tipo_fallo'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
modelos = {
    'Árbol de Decisión': DecisionTreeRegressor(random_state=42,max_depth=20),
    'Random Forest': RandomForestRegressor(n_estimators=25, random_state=42,max_depth=20)
}
resultados = {}
for nombre, modelo in modelos.items():
    modelo.fit(X_train, y_train)
    pred = modelo.predict(X_test)
    
    resultados[nombre] = {
        'Modelo': modelo,
        'R²': r2_score(y_test, pred),
        'MAE': mean_absolute_error(y_test, pred),
        'RMSE': np.sqrt(mean_squared_error(y_test, pred))
    }
df_resultados = pd.DataFrame(resultados).T.round(3)
print("Comparación de modelos:\n")
display(df_resultados)

Comparación de modelos:

,Modelo,R²,MAE,RMSE
Árbol de Decisión,"DecisionTreeRegressor(max_depth=20, random_sta...",0.976534,1.0375,1.540292
Random Forest,"(DecisionTreeRegressor(max_depth=20, max_featu...",0.990413,0.657517,0.984512